### ISSUE TITLE
Examples link broken

### ISSUE THREAD

**Issue by TheDuckDev** [fastjengine/fastjengine.github.io#13]
Section: 
https://fastj.tech/wiki/fastj-basics/fastj-quick-start#:~:text=to%20use%20FastJ%3A-,Example%20Programs,-FastJ%20Documentation
Issue: 
404 Page not found
![image](https://user-images.githubusercontent.com/51789606/151932647-0b18779d-6a7a-4f8a-af45-b94c5affb1af.png)
~~I could've just reported this through Discord but eh this feels more formal~~

**Comment by lucasstarsz** [comment]
Good catch! I'll get those domains updated right away.
